name: deploy forest-restoration to vercel
on: [pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        with:
          node-version: '14'
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn install
      - name: Run tests 
        run: yarn test:ci
      - name: deploy storybook to vercel
        uses: amondnet/vercel-action@v20
        if: startsWith(github.event.payload.pull_request.title, 'shared:') || startsWith(github.event.pull_request.title, 'ui:') || startsWith(github.event.payload.pull_request.title, 'global:') || startsWith(github.event.payload.pull_request.title, 'misc:')
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.ORGID}}
          vercel-project-id: ${{ secrets.STORYBOOKPROJECTID}}
      - name: deploy pwa to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.ORGID}}
          vercel-project-id: ${{ secrets.PROJECTID}}

