name: deploy forest-restoration to vercel
on: [push, pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
- name: Set Env Vars on Vercel Project
  uses: dkershner6/vercel-set-env-action@v1
  with:
    token: ${{ secrets.VERCEL_TOKEN }}
    projectName: forest-restoration-ui
- name: deploy site to vercel
  uses: amondnet/vercel-action@v20
  with:
    vercel-token: ${{ secrets.VERCEL_TOKEN }} 
    vercel-args: '--dev'
    vercel-org-id: ${{ secrets.ORGID}}
    vercel-project-id: ${{ secrets.PROJECTID}}
