name: deploy forest-restoration to vercel
on: [pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        with:
          node-version: '14'
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn install --network-timeout 1000000
      - name: Run tests 
        run: yarn test:ci:u
      - name: deploy storybook to vercel
        uses: amondnet/vercel-action@v20
        if: startsWith(github.event.pull_request.title, 'shared:') || startsWith(github.event.pull_request.title, 'ui:') || startsWith(github.event.pull_request.title, 'global:') || startsWith(github.event.pull_request.title, 'misc:')
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.ORGID}}
          vercel-project-id: ${{ secrets.STORYBOOKPROJECTID}}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        if: startsWith(github.event.pull_request.title, 'shared:') || startsWith(github.event.pull_request.title, 'ui:') || startsWith(github.event.pull_request.title, 'global:') || startsWith(github.event.pull_request.title, 'misc:')
        with:
          workingDir: packages/ui
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: deploy pwa to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-org-id: ${{ secrets.ORGID}}
          vercel-project-id: ${{ secrets.PROJECTID}}

